site_name: 'Microsoft - IdFix'
docs_dir: 'docs'
nav:
  - Home: 'index.md'
  - 'Preperation': 'preperation.md'
  - 'Installation': 'installation.md'
  - 'Operation': 'operation.md'
  - 'Supported Errors': 'supported-errors.md'
  - 'F.A.Q.': 'faq.md'
  - 'Build Documentation': 'build-docs.md'
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
  logo: 'img/logo.png'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
plugins:
  - search
  - markdownextradata
repo_url: https://github.com/microsoft/idfix
site_url: https://microsoft.github.io/idfix